steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - ssh
  - --zone=asia-south2-c
  - g-editor
  - --project=g-codeeditor
  - --command='bash -s'
  - --command='/home/gemcodeeditor/script.sh "proj123"'
options:
  logging: CLOUD_LOGGING_ONLY
