steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - ssh
  - --zone=asia-south2-c
  - g-editor
  - --project=g-codeeditor
- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['-']
  args: ['/home/gemcodeeditor/script.sh','abc']
options:
  logging: CLOUD_LOGGING_ONLY
