name: Run Selenium Tests

on:
  push:
    branches:
      - 1704714149  # Change this to your default branch if different
    paths:
      - 'src/main/java/App.java'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Selenium Server
        run: |
          docker run -d -p 4444:4444 --name selenium-chrome selenium/standalone-chrome:latest

      - name: Build and run Selenium tests
        run: |
          mkdir test-output
          FILE_NAME=reportName.properties

          getProperty() {
            prop_key=$1
            prop_value=$(cat ${FILE_NAME} | grep ${prop_key} | cut -d'=' -f2)
          }
          getProperty reportName
          cd test-output
          > ${prop_value}.txt
          cd ..
          mvn test -DsuiteXmlFile=testng.xml
          # mvn test -DsuiteXmlFile=testng.xml >> ./test-output/${prop_value}.txt
        shell: bash

      - name: list files
        if: always()
        run: |
          ls
          echo
          echo "ls test-output"
          cd test-output
          ls

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test-output

      - name: Download test report
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: test-output

      # New steps for uploading artifacts to GitHub Pages
      - name: Set up Git
        run: |
          git config --global user.email "rahul.adhikari@gemnisolutions.com"
          git config --global user.name "gem-rahulAdhikari"

      - name: Copy files to GitHub Pages directory
        if: always()
        run: |
          # Add commands to copy files to GitHub Pages directory
          cp -R test-output/* .

      - name: Commit and push changes to GitHub Pages
        if: always()
        run: |
          # Stage the changes
          git add .
          # Commit the changes with a message
          git commit -m "Update GitHub Pages"
          # Push the changes to the same branch
          git push origin HEAD
          
      - name: Validate GitHub Pages Accessibility
        if: always()
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" https://gem-rahulAdhikari.github.io/SeleniumIntegration)
          if [ $status_code -eq 200 ]; then
            echo "GitHub Pages is hosted and accessible"
          else
            echo "GitHub Pages is not hosted or inaccessible"
            exit 1
          fi     

      # End of new steps for uploading artifacts to GitHub Pages
